#!/usr/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)

# import tools
source docker-helper
source rd-config
source sv-config
source git-helper
source cmake-helper

# run inside docker instance of $instance_name_rd or "$instance_name_sv"
if ! is_docker_instance "$instance_name_rd" && ! is_docker_instance "$instance_name_sv" ; then
    die "fail: please run it at instance: $instance_name_rd or $instance_name_sv"
fi

# rocprofiler-sdk
if ! setup_repo `
    `"rocprofiler-sdk" `
    `"./rocprofiler-sdk" `
    `"https://github.com/ROCm/rocprofiler-sdk.git" `
    `"amd-staging"; then
    die "fail: clone rocprofiler-sdk"
fi

if ! cmake_build "./rocprofiler-sdk" "all" `
    `-DCMAKE_INSTALL_PREFIX=$ROCM_PATH `
    `-DCMAKE_PREFIX_PATH=$ROCM_PATH; then
    die "fail: build rocprofiler-sdk"
fi

if ! cmake_install ./rocprofiler-sdk/build-release; then
    die "fail: install rocprofiler-sdk"
fi

# aqlprofile, pull 171
if ! setup_repo `
    `"aqlprofile" `
    `"./aqlprofile" `
    `"git@github.com:AMD-ROCm-Internal/aqlprofile" `
    `"amd-staging"; then
    die "fail: clone aqlprofile"
fi

if ! cmake_build "./aqlprofile" "all" `
    `CMAKE_PREFIX_PATH=${ROCM_PATH}/lib:${ROCM_PATH}/include/hsa; then
    die "fail: build aqlprofile"
fi

if ! cmake_install ./aqlprofile/build-release; then
    die "fail: install aqlprofile"
fi

# download and install: rocprof-trace-decoder-ubuntu-22.04-x.x.x-Linux.deb from:
# https://github.com/ROCm/rocprof-trace-decoder/releases

# host: sv-update
