#!/usr/bin/bash
rdh_root="$(realpath ${BASH_SOURCE[0]}|xargs dirname)/.."
source ${rdh_root}/activate
source repo-helper

# base os version
ubuntu_version=22.04

# unified build dash-board:
#    1. http://bas.amd.com/dashboard   -- new server, with uid >= 100000
#    2. http://mkdcvlnxapp01.amd.com/dashboard/  --old server, uid < 100000

# unified_build_id=100913
# below could be manually set if unified_build_id isn't available, or the dashboard server is not available
#    ls_uid <uid>
grfx_build=2249949
rocm_branch=compute-rocm-dkms-no-npi-hipclang
rocm_build=16849
rocm_ver=7.2.0

# search grfx_build grfx_build rocm_build from unified_build_id
if [[ ! -z "$unified_build_id" ]]; then
    if ! verify_amd_unified_build_id "$unified_build_id"; then
        die "fail: unknow unified_build_id $unified_build_id"
    fi
fi

if [[ -z "$grfx_build" || -z "$rocm_branch" || -z "$rocm_build" ]]; then
    die "fail: unknown grfx_build/rocm_branch/rocm_build"
fi

image_name_rd=rocm-${rocm_branch}-${rocm_build}-ubuntu-${ubuntu_version}
instance_name_rd=rocm-dev-${ubuntu_version}