#!/usr/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)

# import tools
source docker-helper
source rd-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

# close old instance
close_container "$instance_name_rd"

# launch shisa in background
if ! docker run -it `
        `--detach `
        `-v ${HOME}/work/shisa:/SHISA/. `
        `-v ${HOME}/work:${HOME}/work `
        `-v ${HOME}/work/vscode-server:/root/.vscode-server `
        `-w ${HOME}/work `
        `--device=/dev/kfd `
        `--device=/dev/dri `
        `--name $instance_name_rd `
        `--hostname $instance_name_rd `
        `$image_name_rd > /dev/null; then
    die "fail to run: $image_name_rd"
fi

# activate rdh
if ! docker exec "$instance_name_rd" `
            `bash -c "echo 'source ${rdh_root}/activate' >> /root/.bashrc"; then
    die "fail: rdh activate"
fi

# default: enter docker
if ! docker exec -it "$instance_name_rd" bash; then
    die "fail: exec $instance_name_rd"
fi

close_container "$instance_name_rd"