#!/usr/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)

# import tools
source docker-helper
source rd-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

# close old instance
close_container "$instance_name_rd"

# launch shisa in background
if ! docker run -it `
        `--detach `
        `-v ${HOME}/work/shisa:/SHISA/. `
        `-v ${HOME}:${HOME} `
        `-w ${HOME}/work `
        `--device=/dev/kfd `
        `--device=/dev/dri `
        `--cap-add=SYS_PTRACE `
        `--security-opt seccomp=unconfined `
        `--name $instance_name_rd `
        `--hostname $(hostname -s)/$instance_name_rd `
        `$image_name_rd > /dev/null; then
    die "fail to run: $image_name_rd"
fi

if (( $# == 0 )); then
    # default: enter docker
    docker exec -it "$instance_name_rd" bash
    ret_code=$?
    if (( ret_code != 0 )); then
        log "docker exec $instance_name_rd return fail code ($ret_code)"
    fi
    close_container "$instance_name_rd"
fi