#!/bin/bash
# usage: source activate
RDH_ROOT="$(dirname $(realpath "${BASH_SOURCE[0]}"))"

# expose dirs:
scripts_dir=${RDH_ROOT}/scripts
util_dir=${RDH_ROOT}/scripts/util
shisa_dir=${RDH_ROOT}/shisa
misa_dir=${RDH_ROOT}/misa
PATH=${scripts_dir}:${util_dir}:${shisa_dir}:${misa_dir}:$PATH

# expose git helper functions
source tools
source git-cmd-helper