#!/bin/bash

function install_docker_engine() {
    # install doc engine
    # remove unofficial doc engine pkgs. Ubuntu 24.04 repos has all of them
    control_pkgs "docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc" 2

    # install two dependencies
    control_pkgs "ca-certificates curl" 1

    # Add GPG key
    if [[ ! -f "/etc/apt/keyrings/docker.asc" ]]; then
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
    fi
    
    # Add the repository to Apt sources:
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update

    # install pkgs
    control_pkgs "docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin" 1
    # verify
    if ! sudo docker run hello-world; then
        die "failed to install doc engine"
    else
        log "doc eninge installed successfully"
    fi
}