#!/bin/bash
# helper to manage packages

function is_pkg_installed() {
    local pkg="$1"
    if dpkg -l "$pkg" 2>/dev/null | grep ^.i &>/dev/null; then
        return 0
    else
        return -1
    fi
}

function get_pkg_version() {
    local pkg="$1"
    dpkg -l "$pkg" 2>/dev/null | awk '/ii/{print $3}'
}

function is_pkg_held() {
    local pkg="$1"
    if dpkg -l "$pkg" 2>/dev/null | grep ^hi &>/dev/null; then
        return 0
    else
        return -1
    fi
}

# $1: package list
# $2: control operations
#       1 install
#       2 uninstall
#       3 hold pkgs
#       4 unhold pkgs
# Todo: Ubuntu only
function control_pkgs() {
    local pkgs="$1"
    local op="$2"

    local pkg
    for pkg in $pkgs; do
        if is_pkg_installed "$pkg"; then
            if (( op == 2 )); then
                # uninstall
                if ! sudo apt-get remove "$pkg" -y; then
                    die "failed to uninstall package: $pkg"
                fi
            fi

            local hold_status=0
            if is_pkg_held "$pkg"; then
                hold_status=1
            fi
            if (( op == 3 && hold_status == 0 )); then
                # hold package
                if ! sudo apt-mark hold "$pkg"; then
                    die "failed to hold package: $pkg"
                fi
            fi
            if (( op == 4 && hold_status == 1 )); then
                # unhold package
                if ! sudo apt-mark unhold "$pkg"; then
                    die "failed to unhold package: $pkg"
                fi
            fi
        else
            if (( op == 1 )); then
                # install
                if ! sudo apt-get install "$pkg" -y; then
                    die "failed to install package: $pkg"
                fi
            fi
        fi
    done
    return 0
}

function prefer_pkgs() {
    local pkgs="$1"
    local op="$2"
    local prefer_file="/etc/apt/preferences.d/$3"

    [[ -f "$prefer_file" ]] && sudo rm -r "$prefer_file"
    if (( op == 1 )); then
        local pkg
        for pkg in $pkgs; do
            if is_pkg_installed "$pkg"; then
                local version=$(get_pkg_version "$pkg")
                printf  "Package: %s\n`
                        `Pin: version %s\n`
                        `Pin-Priority: 600\n\n" `
                        `"$pkg" "$version" |`
                        `sudo tee -a "$prefer_file" $>/dev/null
            fi
        done
    fi
    if ! sudo apt-get update -y; then
        die "failed to update repo"
    fi
}
