#!/usr/bin/bash
# create docker image to for gpu interface build
# make tools available
bin_dir=$(realpath $0|xargs dirname)
util_dir=$(dirname $bin_dir)/scripts/util
PATH=${bin_dir}:${util_dir}:$PATH
SELF_TAG="[$(basename $0)]"

# import tools
source tools
source docker-helper
source gi-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

# dockerfile
docker_file="$(dirname $bin_dir)/dockerfile/gpu_interface.dockerfile"

# docker build
log "docker build: $image_name"
if ! docker build -t "$image_name" `
                 `-f $docker_file `
                 `--build-arg ROCM_VERSION=$rocm_version `
                 `--build-arg ROCM_OS_VERSION=$rocm_os_version .; then
    die "fail to build: $image_name"
fi
log "docker build success: $image_name"