#!/usr/bin/bash
# create docker image to for gpu interface build
# expose rdh
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)
SELF_TAG="[$(basename $0)]"

# import tools
source docker-helper
source gi-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

# dockerfile
docker_file="${rdh_root}/dockerfile/gpu_interface.dockerfile"

# docker build
log "docker build: $image_name_gi"
if ! docker build -t "$image_name_gi" `
                 `-f $docker_file `
                 `--build-arg ROCM_VERSION=$rocm_version `
                 `--build-arg ROCM_OS_VERSION=$rocm_os_version .; then
    die "fail to build: $image_name_gi"
fi
log "docker build success: $image_name_gi"