#!/usr/bin/bash
# make tools available
bin_dir=$(realpath $0|xargs dirname)
util_dir=$(dirname $bin_dir)/scripts/util
PATH=${bin_dir}:${util_dir}:$PATH
SELF_TAG="[$(basename $0)]"

# import tools
source tools
source docker-helper
source gi-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

# launch gpu interface
docker run -it --rm `
        `-v ${HOME}/work/il/SHISA_min:/SHISA/. `
        `-e SHISA=/SHISA `
        `-v ${HOME}/work:${HOME}/work `
        `-v ${HOME}/work/.ssh:/root/.ssh `
        `-v ${HOME}/work/vscode-server:/root/.vscode-server `
        `--device=/dev/kfd `
        `--device=/dev/dri `
        `-w ${HOME}/work/il/ `
        `--group-add video `
        `--cap-add=SYS_PTRACE `
        `--security-opt seccomp=unconfined `
        `--name $instance_name `
        `--hostname $instance_name `
        `-e CONTAINER_NAME=$instance_name `
        `$image_name

if (( $? != 0 )); then
    die "fail to run: $image_name"
fi
