#!/usr/bin/bash
rdh_root="$(realpath ${BASH_SOURCE[0]}|xargs dirname)/.."
SELF_TAG="[$(basename ${BASH_SOURCE[0]})]"

source gi-config
source docker-helper
source cmake-helper

function setup_rocr() {
    local target=$1

    # clone source
    if ! refresh_dir "$target"; then
        die "fail to create: $target"
    fi

    if ! git clone https://github.com/RadeonOpenCompute/ROCR-Runtime -b rocm-$rocm_version_gi $target; then
        die "fail to clone ROCR-Runtime"
    fi

    # Do not check start timestamp validity in hsa_amd_profiling_get_dispatch_time because it can be buggy with multiple Submit() calls
    # Keep the check for the end timestamp, which is what HsaDriver reads and which works correctly in testing
    sed -i 's/(start == 0) || (end == 0) || (start < t0_.GPUClockCounter)/(end == 0)/' $target/runtime/hsa-runtime/core/runtime/amd_gpu_agent.cpp

    # build
    if ! cmake_build $target `
                    `all `
                    `-DBUILD_SHARED_LIBS=OFF `
                    `-DClang_DIR=/opt/rocm/lib/llvm/lib/cmake/clang; then 
        die "fail: build $dir"
    fi
    return 0
}

function clone_gi() {
    local target=$1

    if ! refresh_dir "$target"; then
        die "fail to create: $target"
    fi

    # setup to store pat 
    # if ! git config --global url."git@github.com:".insteadOf "https://github.com/"; then
    #    die "fail: git credential store"
    #fi

    # clone gpu_interface and sub modules(pal_navi, pal_vega)
    local branch_opt
    if [[ ! -z "${gi_branch}" ]]; then
        branch_opt="-b ${gi_branch}"
    fi

    # clone from https://github.com/LibAmd/SHISA_gpu_interface.git
    if ! git clone git@github.com:LibAmd/SHISA_gpu_interface.git $branch_opt $target; then
        die "fail to clone: https://github.amd.com/LibAmd/SHISA_gpu_interface"
    fi

    # clone dependency: ./drivers at https://github.com/AMD-Radeon-Driver/drivers.git
    pushd "$target"
    if ! git init drivers; then
        die "fail to init drivers"
    fi

    cd drivers
    if ! git sparse-checkout set drivers/pxproxy drivers/inc/asic_reg drivers/inc/shared drivers/dx/dxx/vam; then
        die "fail to sparse-checkout from drivers"
    fi

    if ! git remote add origin git@github.com:AMD-Radeon-Driver/drivers.git; then
        die "fail to add origin repo"
    fi

    if ! git pull --depth 1 origin amd/release/23.30; then
        die "fail to pull amd/release/23.30 from drivers"
    fi
    mv drivers/pxproxy drivers/inc drivers/dx/dxx/vam .
    cd ..


    if ! git submodule update --init; then
        die "fail: update submodules"
    fi

    # apply patch to pal_navi 
    cd pal_navi
    if ! git apply ../0001-PAL_CLIENT_SHISA.pal_navi.patch; then
        die "fail: apply navi patch to pal_navi"
    else
        git status
    fi

    # apply patch to pal_vega
    cd ../pal_vega
    if ! git apply ../0001-PAL_CLIENT_SHISA.pal_vega.patch; then
        die "fail: apply vega patch to pal_vega"
    else
        git status
    fi
    if ! git submodule update --init; then
        die "fail: update submodules"
    fi

    # change Developer-Solutions to AMD-Developer-Solutions in .gitmodules
    sed -i 's/Developer-Solutions/AMD-Developer-Solutions/' shared/devdriver/.gitmodules
    cd ..
    if ! git submodule update --init --recursive; then
        die "fail: update submodules"
    fi

    cd pal_navi
    # fix syntax errors in pal_navi/shared/devdriver/shared/legacy/inc/util/queue.h
    # sed -i 's/\(: Queue(rhs\.\)allocCb\()\)/\1m_allocCb\2/' ./shared/devdriver/shared/legacy/inc/util/queue.h

    # fix syntax error in pal_navi/shared/devdriver/third_party/rapidjson/include/rapidjson/document.h
    sed -i 's/const SizeType length;/SizeType length;/' ./shared/devdriver/third_party/rapidjson/include/rapidjson/document.h

    return 0
}

function build_gi() {
    local target=$1

    mkdir -p /SHISA/bin /SHISA/binDebug
    pushd $target
    if ! cmake_build . `
                `Release `
                `-DGPU_INTERFACE_PAL_SUPPORT=ON `
                `-DGPU_INTERFACE_HSA_SUPPORT=ON; then
        die "fail: build release gpu_interface"
    fi

    if ! cmake_build . `
                `Debug `
                `-DGPU_INTERFACE_PAL_SUPPORT=ON `
                `-DGPU_INTERFACE_HSA_SUPPORT=ONS; then
        die "fail: build debug gpu_interface"
    fi
    popd
}


function install_gi() {
    local target=$1

    mkdir -p /SHISA/bin /SHISA/binDebug
    pushd $target
    if ! cmake --build ./build-release; then
        die "fail: install release gpu_interface"
    fi

    if ! cmake --build ./build-debug; then
        die "fail: install debug gpu_interface"
    fi
    popd
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "$1" == "1" ]]; then
        # clone_gi gpu_interface
        python3 ${rdh_root}/scripts/putil/clone_gi.py gpu_interface
    else
        # run inside docker instance of $instance_name_gi
        if ! is_docker_instance $instance_name_gi; then
            die "fail: please run it at instance: $instance_name_gi"
        fi

        build_gi gpu_interface

        # libgpu_interface.<version>.so
        log "======================results: gpu_interface=================="
        find "$SHISA" -name "libgpu_interface.*.so"
    fi
fi