#!/usr/bin/bash
# make tools available
bin_dir=$(realpath $0|xargs dirname)
util_dir=$(dirname $bin_dir)/scripts/util
PATH=${bin_dir}:${util_dir}:$PATH
SELF_TAG="[$(basename $0)]"

# import tools
source tools
source docker-helper

# run inside docker
if is_inside_docker; then
    log "container: $(hostname)"
else
    log "host: $HOSTNAME"
fi
