#!/usr/bin/bash
# expose rdh
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)
SELF_TAG="[$(basename $0)]"

# import tools
source docker-helper

# run inside docker
if is_inside_docker; then
    log "container: $(hostname)"
else
    log "host: $HOSTNAME"
fi
