#!/usr/bin/bash
rdh_root="$(realpath ${BASH_SOURCE[0]}|xargs dirname)/.."
source ${rdh_root}/activate
source shisa-helper
source rd-config

rocm_version=6.4.1
rocm_os_version=24.04
image_name=shisa-ubuntu-$rocm_os_version-rocm-$rocm_version
instance_name=shisa

# rocm internal images, override rocm_version, rocm_os_version and image_name
rocm_internal_image=$image_name_rd
if [[ ! -z "$rocm_internal_image" ]]; then
    image_name=shisa-ubuntu-$rocm_os_version-rocm-${rocm_branch}-${rocm_build}
fi

GFX_VERSION=$(get_gfx_version)
if [[ -z "$GFX_VERSION" ]]; then
    die "fail: gfx version unknown"
fi

SP3_ASIC=$(get_sp3_asic $GFX_VERSION)
if [[ -z "$SP3_ASIC" ]]; then
    die "fail: SP3_ASIC unknown"
fi

TT_OPTS="$(get_tt_opts $GFX_VERSION)"
if [[ -z "$TT_OPTS" ]]; then
    die "fail: TT_OPTS unknown"
fi

# GPU architecture
architecture="gfx942;gfx950"