#!/usr/bin/bash
rocm_version=6.4.1
rocm_os_version=22.04
image_name=shisa-ubuntu-$rocm_os_version-rocm-$rocm_version
instance_name=shisa

# MI350 
SP3_ASIC=MI350
TT_OPTS="-a GFX9"
GFX_VERSION=gfx950

# MI300
#SP3_ASIC=MI300
#TT_OPTS="-a GFX9"
#GFX_VERSION=gfx942
