#!/usr/bin/bash
# create docker image: shisa-docker-<rocm version>
# expose rdh
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)
SELF_TAG="[$(basename $0)]"

# import tools
source tools
source docker-helper
source s-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

# dockerfile
docker_file="${rdh_root}/dockerfile/shisa.dockerfile"

# docker build
log "docker build: $image_name"
if ! docker build -t "$image_name" `
                 `-f $docker_file `
                 `--build-arg ROCM_VERSION=$rocm_version `
                 `--build-arg ROCM_OS_VERSION=$rocm_os_version `
                 `--build-arg SP3_ASIC=$SP3_ASIC `
                 `--build-arg TT_OPTS="$TT_OPTS" .; then
    die "fail to build: $image_name"
fi
log "docker build success: $image_name"
