#!/usr/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)

# import tools
source docker-helper
source s-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

# close old instance
close_container "$instance_name"

#        `-e SHISA_HSA_PM4_MODE=1 `
#        `-e SHISA_HSA_TIMEOUT_SECONDS=1 `
#        `-e LD_LIBRARY_PATH=/SHISA/bin-hip-6.5/:/SHISA/bin:/opt/rocm/lib/llvm/lib `

# launch shisa in background
work_dir=$(realpath "${HOME}/work")
if ! docker run -it `
        `--detach `
        `-v ${work_dir}/shisa:/SHISA/. `
        `-v ${HOME}:${HOME} `
        `-v ${work_dir}:${work_dir} `
        `-w ${work_dir}/shisa `
        `-p 127.0.0.1:9346:9339 `
        `--device=/dev/kfd `
        `--device=/dev/dri `
        `--name $instance_name `
        `--hostname $(hostname -s)/$instance_name `
        `$image_name > /dev/null; then
    die "fail to run: $image_name"
fi

# enter or run setup
if (( $# == 0 )); then
    # default: enter docker
    if ! docker exec -it "$instance_name" bash; then
        die "fail: exec $instance_name"
    fi
else 
    # shisa setup
    if ! docker exec -it "$instance_name" bash -c "cd ../shisa;${HOME}/work/rdh/shisa/s-setup"; then
        die "fail: setup shisa"
    fi
fi

close_container "$instance_name"