#!/usr/bin/bash
# make tools available
bin_dir=$(realpath $0|xargs dirname)
util_dir=$(dirname $bin_dir)/scripts/util
PATH=${bin_dir}:${util_dir}:$PATH
SELF_TAG="[$(basename $0)]"

# import tools
source tools
source docker-helper
source s-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

#        `-e SHISA_HSA_PM4_MODE=1 `
#        `-e SHISA_HSA_TIMEOUT_SECONDS=1 `

docker run -it --rm `
        `-v ${HOME}/work/il/SHISA_min:/SHISA/. `
        `-v ${HOME}/work:${HOME}/work `
        `-v ${HOME}/work/vscode-server:/root/.vscode-server `
        `-w ${HOME}/work/misa `
        `-e SHISA_HSA_PM4_MODE=1 `
        `-e LD_LIBRARY_PATH=/SHISA/bin-hip-6.5/:/SHISA/bin:/opt/rocm/lib/llvm/lib `
        `-p 127.0.0.1:9346:9339 `
        `--device=/dev/kfd `
        `--device=/dev/dri `
        `--name $instance_name `
        `--hostname $instance_name `
        `$image_name

if (( $? != 0 )); then
    die "fail to run: $image_name"
fi
