#!/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)
SELF_TAG="[$(basename $0)]"

# import tools
source docker-helper
source cmake-helper
source s-config

# run inside docker instance of $instance_name
if ! is_docker_instance $instance_name; then
    die "fail: please run it at instance: $instance_name"
fi

build_list="test_apps/conv_test `
           `test_apps/misa_conv_test `
           `tools/shader_build `
           `sp3/backend_v3 `
           `sp3/hardened_v2 "

for target in $build_list; do
    log "======================== build $target =========================="
    if ! cmake_build $target "all"; then 
        die "fail: build $target"
    fi
    log "==================== build $target: success ====================="
done

# build ShaderProcessor-exe
target=tools/shader_processor
log "======================== build $target =========================="
chown -R root:root ./tools/shader_processor
pushd ./tools/shader_processor
if ! stack install --local-bin-path /SHISA/bin; then
    die "fail: $target"
fi
popd
log "==================== build $target: success ====================="