#!/usr/bin/bash
# make tools available
bin_dir=$(realpath $0|xargs dirname)
util_dir=$(dirname $bin_dir)/scripts/util
PATH=${bin_dir}:${util_dir}:$PATH
SELF_TAG="[$(basename $0)]"

# import tools
source tools
source docker-helper
source s-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

src_file="./shisa_src.tar.gz"
if (( $# == 1 )); then
    src_file=$1
fi

target="./shisa"
if (( $# == 2 )); then
    src_file=$1
fi

if ! extract "$src_file" "$target"; then
    die "fail: unpack $src_file to $target"
fi