#!/usr/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

bin_dir=$(realpath $0|xargs dirname)
SELF_TAG="[$(basename $0)]"

source docker-helper
source s-config

if is_inside_docker; then
    die "Cannot run inside docker!"
fi

# Parse arguments
src_file="${1:-./shisa_src.tar.gz}"
target="${2:-./shisa}"
if [[ ! -f "$src_file" ]]; then
    die "Tarball not found: $src_file"
fi

if ! extract "$src_file" "$target"; then
    die "Failed to unpack $src_file to $target"
fi