#!/usr/bin/bash
# expose rdh
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir="$(realpath $0|xargs dirname)"
SELF_TAG="[$(basename $0)]"

# import tools
source docker-helper
source s-config
source m-config

function m-parse() {
    local result_dir=$1
    local misa_root="./$misa_branch"
    if [ ! -d "$misa_root" ]; then
        die "fail: can't locate misa root: ./$misa_branch"
    fi

    local misa_conv_test_scripts="${shisa_root}/test_apps/misa_conv_test/scripts"

    ${misa_conv_test_scripts}/combine.pl -k ${misa_conv_test_scripts}/kern_list_all.txt -c ${result_dir}/case_stat.txt $result_dir > ${result_dir}/out.txt

    # collect
    local stat=${work_root}/stat/$(basename $result_dir)
    mkdir -p $stat
    cp ${result_dir}/out.txt ${result_dir}/case_stat.txt "$stat"
}

result_dir=$RESDIR
if (( $# == 1 )); then
    result_dir=$1
fi

m-parse "$result_dir"