#!/usr/bin/bash
# sudo apt-get install libfile-slurp-perl -y
# sudo apt install liblist-moreutils-perl -y
# make tools available
bin_dir=$(realpath $0|xargs dirname)
util_dir=$(dirname $bin_dir)/scripts/util
shisa_dir=$(dirname $bin_dir)/shisa
PATH=${bin_dir}:${util_dir}:${shisa_dir}:$PATH
SELF_TAG="[$(basename $0)]"

# import tools
source tools
source docker-helper
source s-config
source m-config

function m-parse() {
    local misa_root="./$misa_branch"
    if [ ! -d "$misa_root" ]; then
        die "fail: can't locate misa root: ./$misa_branch"
    fi

    local misa_conv_test_scripts="${shisa_root}/test_apps/misa_conv_test/scripts"

    ${misa_conv_test_scripts}/combine.pl -k ${misa_conv_test_scripts}/kern_list_all.txt -c ${RESDIR}/case_stat.txt $RESDIR > ${RESDIR}/out.txt

    # collect
    local stat=${work_root}/stat/$(basename $RESDIR)
    mkdir -p $stat
    cp ${RESDIR}/out.txt ${RESDIR}/case_stat.txt "$stat"
}

m-parse