#!/bin/bash
# expose rdh
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir="$(realpath $0|xargs dirname)"
SELF_TAG="[$(basename $0)]"

# import tools
source docker-helper
source s-config
source m-config

function full_test() {
    local misa_root="./$misa_branch"
    if [ ! -d "$misa_root" ]; then
        die "fail: can't find misa root: ./$misa_branch"
    fi

    # generate/cache test-list
    ${bin_dir}/m-list-test > test-list
    mv test-list "$RESDIR"
    
    # cat "$RESDIR"/test-list | parallel -j 8
    local device
    for (( device = 0 ; device < 8 ; device++ )); do
        cat "$RESDIR"/test-list | grep -- "--device $device"  | parallel -j 1 &
    done
    return 0
}

# run inside docker instance of $instance_name
if ! is_docker_instance $instance_name; then
    die "fail: please run it at instance: $instance_name"
fi

full_test
