#!/usr/bin/bash
rdh_root="$(realpath ${BASH_SOURCE[0]}|xargs dirname)/.."
source ${rdh_root}/activate
source rd-config

image_name_sv=solver-${image_name_rd}
instance_name_sv=solver

# code branch
solver_src_root=./solver