#!/usr/bin/bash
# create docker image: shisa-docker-<rocm version>
# expose rdh
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)
SELF_TAG="[$(basename $0)]"

# import tools
source docker-helper
source sv-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

close_container "$instance_name_sv"

# open a rd-docker
if ! rd-open setup; then
    die "fail: open $image_name_rd"
fi

# run 
if ! docker exec -it "$instance_name_rd" bash -c "${rdh_root}/solver/sv-build-solver"; then
    # die "fail: setup gpu-interface"
    log "fail: setup gpu-interface"
fi

# store "$instance_name_rd" to 
if ! docker commit "$instance_name_rd" "$image_name_sv"; then
    die "fail: create $image_name_sv"
fi

close_container "$instance_name_sv"