#!/usr/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)

# import tools
source docker-helper
source sv-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

# close old instance
close_container "$instance_name_sv"

# launch docker in background
if ! docker run -it `
        `--detach `
        `-v ${HOME}/work/shisa:/SHISA/. `
        `-v ${HOME}:${HOME} `
        `-w ${HOME}/work `
        `--device=/dev/kfd `
        `--device=/dev/dri `
        `--cap-add=SYS_PTRACE `
        `--security-opt seccomp=unconfined `
        `-p 127.0.0.1:9346:9339 `
        `--name $instance_name_sv `
        `--hostname $(get_host_alias)/$instance_name_sv `
        `$image_name_sv > /dev/null; then
    die "fail to run: $image_name_sv"
fi

# default: enter docker
docker exec -it "$instance_name_sv" bash
ret_code=$?
if (( ret_code != 0 )); then
    log "docker exec $instance_name_sv return fail code ($ret_code)"
fi
close_container "$instance_name_sv"