#!/usr/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)

# import tools
source docker-helper
source sv-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

# close old instance
close_container "$instance_name_sv"

# launch docker in background
if ! docker run -it `
        `--detach `
        `-v ${HOME}/work/shisa:/SHISA/. `
        `-v ${HOME}:${HOME} `
        `-w ${HOME}/work `
        `--device=/dev/kfd `
        `--device=/dev/dri `
        `--cap-add=SYS_PTRACE `
        `--security-opt seccomp=unconfined `
        `-p 127.0.0.1:9346:9339 `
        `--name $instance_name_sv `
        `--hostname $(hostname -s)/$instance_name_sv `
        `$image_name_rd > /dev/null; then
    die "fail to run: $image_name_sv"
fi

# enter or run setup
if (( $# == 0 )); then
    # default: enter docker
    if ! docker exec -it "$instance_name_sv" bash; then
        die "fail: exec $instance_name_sv"
    fi
else 
    # solver setup
    if ! docker exec -it "$instance_name_sv" bash -c "cd ../shisa;${rdh_root}/shisa/s-setup"; then
        die "fail: setup solver"
    fi
fi

close_container "$instance_name_sv"