#!/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)
SELF_TAG="[$(basename $0)]"

# import tools
source docker-helper
source cmake-helper
source sv-config

# run inside docker instance of $instance_name_sv
if ! is_docker_instance $instance_name_sv; then
    die "fail: please run it at instance: $instance_name_sv"
fi

# clone rocblas
blas_src=$(realpath ./rocblas)
refresh_dir "$blas_src"
if ! git clone -b "$blas_branch" https://github.com/ROCm/rocBLAS.git "$blas_src"; then
    die "fail: clone rocblas $blas_branch"
fi

pushd "$blas_src"
# build dependency and  release 
if ! ./install.sh -d; then
    die "fail: build release rocblas $blas_branch"
fi

# build debug
if ! ./install.sh --debug; then
    die "fail: build release rocblas $blas_branch"
fi
popd
