#!/usr/bin/bash
rdh_root="$(realpath $0|xargs dirname)/.."
source ${rdh_root}/activate

# expose self
bin_dir=$(realpath $0|xargs dirname)

# import tools
source docker-helper
source sv-config

# run at host
if is_inside_docker; then
    die "fail: cannot run inside docker!"
fi

if ! docker commit "$instance_name_sv" "$image_name_sv"; then
    die "fail: commit ${instance_name_sv} to ${image_name_sv}" 
fi